### ISSUE TITLE
TODO List for 2024

### ISSUE THREAD

**Issue by CraigRoss95** [CraigRoss95/Website#3]
OVERALL:

- [x] Implement content manager
- [x] Implement skeleton manager
- [x] Fix left right scroll bar appearing on every page
- [x] Make side bars smaller
- [x] Make background green (new pallet too)
- [x] Put page header in its own file
- [x] Put page footer in its own pile
- [x] Remove ".html"from URL (https://stackoverflow.com/questions/21244910/remove-html-extension-from-github-pages)
- [x] ~~Rename index page to home page (https://stackoverflow.com/questions/37079910/options-for-changing-the-directory-index-when-using-github-pages)~~ (fixed by above)
- [x] ~~block hidden pages~~ (No need)
- [x] Fix clipping on contact bar background
- [x] JSON storage for content 
- [x] update doggy Easter egg
- [x] Load background from top to bottom (avoid mismatch at top of screen)
- [x] Make Navbar bigger on mobile (collapsible nav bar)
- [x] Add email to contact
- [x] Add vague address (Newton MA)
- [x] Add icons to Navbar 
- [x] Add icons to contact
- [x] Fix styling on contact (make them that goldenrod color)
- [x] **Fix white flash**
- [x] Clean up CSS
- [x] Collapsible contact bar
- [x] Fix nav-bar not following
- [x] Fix Nav-bar popping in instead of fading
- [x] Center new icons
- [x] ~~Move nav-bar to hug left on mobile~~ (looks awful)
- [x] Seperate CSS files (header, footer, site, portfolio)
- [x] Rename CSS class "nav-bar-options" (conflicts with "nav-bar-option", maybe "nav-bar-option-container"?)
- [x] ~~Add Fade out~~ Obsolete now because of js served content field
- [x] JS served content field (we will call it "URL Gaslighting"
- [x] Update titles
- [x] Fix Portfolio page too wide
- [x] Change repo name
- [x] Fix zoom issue (zoom out to to 40% and the site goes to the left)
- [x] Scroll to top on clicking tab
- [x] Add minimum text size (stop text from getting too small
- [x] Try static background (loads first but large and would have to underlap existing content and replace green flash)
- [x] Add README
- [x] Get rid of unused code (fade out keep fade in for initial loading)
- [x] Fade in background then content?
- [x] Add blog tab to top bar with coming soon alert
- [x] rename "header" to "nav-bar" (and "footer" to "contact-bar")
- [x] Deploy Blogs feature
- [x] add header ~~and footer~~ content row (don't need it now, maybe later?

-BLOG
- [x] Add forward and back buttons
- [x] Add date and blog link (add to content template but make it hidden for about and other page
- [x] have blog id query only get blog ids and not the whole feed
- [x] Find way to put blog date and link at bottom of window
- [x] Add better CSS to header.
- [x] Finish blog Proxy Repo

INDEX:
- [x] Add image to top of screen
- [x] #15
- [x] Use cartoon picture for dev at work
- [x] Change work experience section to reflect time at FIS
- [x] Update skills (also fix formatting (use bootstrap table?)
- [x] Add Skill Icons (use this: https://devicon.dev/)
- [x] Move skills higher

PORTFOLIO:
- [x] **Convert portfolio contents object to JSON**
- [x] Move button icon src to JSON
- [x] Add hint above portfolio buttons 
- [x] Use transparent images where relevant
- [x] Remove hard coding of FIS section as default (have it use a the first in the array instead)
- [x] Make image smaller
- [x] Add skills used section updated by JSON
- [x] Add date that updates by JSON
- [x] ~~Make text block wider on portfolio section~~ Looks good after other CSS changes
- [x] ~~Update website photo (make it 800 by 400)~~ Looks good after other CSS changes
- [x] Make FIS Worldpay section more clear (add reason for leaving)
- [x] Change look of JS button and make it more clear which one has been selected
- [x] Add Link to project
- [x] Icon row clipping on mobile

-OTHER PAGE:
- [x] Change beans recipe to low sugar one
- [x] Add DJ skills to Other
- [x] Add NAS + Photoscanning
- [x] Fix scroll to top not always working (scroll to bottom on index and then click any other page to reproduce)
- [x] Change "My Family" section picture to lower quality image
- [x] Update DJ picture

-PHOTO ZOOM
- [x] Zoom in on image on click site wide (too ambitious?)
- [x] Fix sideways mobile zoom putting picture off screen
- [x] Move css to new file
- [x] ~~add red 'X' to top left corner (or say click anywhere to go back)~~ Reminder text will suffice 

-STRETCH GOALS
- [x] Add alert for petting Dixie 10 times
